apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: apr3-codegen-vllm-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/apr3-codegen-vllm-1:c2f5812643a9829f91ca6cbc8b9d0140f0249d10@sha256:3dbd4d17093e73969040ad414a4a71572bc4911ec35553f8b1b5dfb4905fe395 # use pre-built to bootstrap
          name: app-inference
